version: 0.2

phases:
  build:
    commands:
      - aws s3 sync templates s3://$TEMPLATE_BUCKET --delete
      - aws cloudformation package --template templates/main.yaml --s3-bucket $TEMPLATE_BUCKET --output-template-file packaged-root-template.yaml

artifacts:
  files:
    - packaged-root-template.yaml
    - config-*.json
