AWSTemplateFormatVersion: 2010-09-09
Description: Backend certificate stack.
Parameters:
  DomainName:
    Type: String
    Description: Name of full domain including subdomain.

  HostedZoneId:
    Type: String
    Description: Hosted Zone ID

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: ARN of Certificate.
    Value: !Ref Certificate
    Export:
      Name:
        Fn::Join:
          - '-'
          - - !Ref AWS::StackName
            - CertificateArn
