AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  KeyName:
    Type: String

  NetworkStack:
    Type: String

  ALBStack:
    Type: String

Resources:
  OpenviduSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Openvidu security group
      VpcId:
        Fn::ImportValue:
          Fn::Join:
            - '-'
            - - !Ref NetworkStack
              - VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId:
            Fn::ImportValue:
              Fn::Join:
                - '-'
                - - !Ref ALBStack
                  - OpenviduAlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId:
            Fn::ImportValue:
              Fn::Join:
                - '-'
                - - !Ref ALBStack
                  - OpenviduAlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId:
            Fn::ImportValue:
              Fn::Join:
                - '-'
                - - !Ref ALBStack
                  - OpenviduAlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 3478
          ToPort: 3478
          SourceSecurityGroupId:
            Fn::ImportValue:
              Fn::Join:
                - '-'
                - - !Ref ALBStack
                  - OpenviduAlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 40000
          ToPort: 65535
          SourceSecurityGroupId:
            Fn::ImportValue:
              Fn::Join:
                - '-'
                - - !Ref ALBStack
                  - OpenviduAlbSecurityGroup
        - IpProtocol: udp
          FromPort: 3478
          ToPort: 65535
          SourceSecurityGroupId:
            Fn::ImportValue:
              Fn::Join:
                - '-'
                - - !Ref ALBStack
                  - OpenviduAlbSecurityGroup

  OpenviduLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t3.large
        KeyName: !Ref KeyName
        ImageId: ami-0e6f2b2fa0ca704d0
        SecurityGroupIds:
          - !Ref OpenviduSecurityGroup
        UserData:
          Fn::Base64: |
            #!/bin/bash
            apt update -y
            apt-get install -y ca-certificates curl
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            chmod a+r /etc/apt/keyrings/docker.asc
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update -y
            apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            cd /opt
            curl https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/install_openvidu_latest.sh -o install_openvidu_latest.sh
            bash install_openvidu_latest.sh &
            PID=$!
            sleep 40
            if ps -p $PID > /dev/null; then
            echo "OpenVidu installation script timed out."
            kill $PID
            exit 1
            fi
            cd /opt/openvidu
            sed -i 's/DOMAIN_OR_PUBLIC_IP=/DOMAIN_OR_PUBLIC_IP=openvidu.syeong.link/g' .env
            sed -i 's/OPENVIDU_SECRET=/OPENVIDU_SECRET=hongaldan/g' .env
            sed -i 's/CERTIFICATE=/CERTIFICATE=letsencrypt/g' .env
            sed -i 's/LETSENCRYPT_EMAIL=/LETSENCRYPT_EMAIL=visioner2168@gmial.com/g' .env
            ./openvidu start


  OpenviduASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue:
            Fn::Join:
              - '-'
              - - !Ref NetworkStack
                - PrivateSubnet1
        - Fn::ImportValue:
            Fn::Join:
              - '-'
              - - !Ref NetworkStack
                - PrivateSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref OpenviduLaunchTemplate
        Version: 1
      MinSize: '1'
      MaxSize: "10"
      DesiredCapacity: '1'
      TargetGroupARNs:
        - Fn::ImportValue:
            Fn::Join:
              - '-'
              - - !Ref ALBStack
                - OpenviduTargetGroup
        - Fn::ImportValue:
            Fn::Join:
              - '-'
              - - !Ref ALBStack
                - OpenviduTargetGroupHTTPS
